num = int(input())
new_set1 = set()
new_set2 = set()
for each in range(1,num+1):
    new_set1.add(each * 2)
    new_set2.add(each * 3)
differrence = new_set1.difference(new_set2)
sy_difference = new_set1.symmetric_difference(new_set2)
differrence = list(differrence)
sy_difference = list(sy_difference)
differrence.sort()
sy_difference.sort()
print(differrence)
print(sy_difference)